name: Build

on:
  workflow_dispatch: # Manual trigger
    inputs:
      job-to-fail:
        description: The job that should fail for testing purposes.
        type: string
        required: false
        default: 'none'

permissions:
  contents: read

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Build
        run: sleep 10 && echo 'Hello, world (${{ matrix.os }})'
      - name: Fail
        if: ${{ inputs.job-to-fail == 'build' }}
        run: exit 1
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    strategy:
      fail-fast: false
      matrix:
        jdk: [ '17', '21' ]
    with:
      job-to-fail: ${{ inputs.job-to-fail }}
      java-version: ${{ matrix.jdk }}
  send-notification:
    name: Send Notification 1
    needs: [ test ]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        run: echo "This would send a notificaiton"
  send-notification2:
    name: Send Notification 2
    needs: [ test ]
    env: 
      NEEDS_CONTEXT: ${{ toJSON(needs) }}
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        run: |
          echo "This would send a notificaiton"
          echo $NEEDS_CONTEXT
  send-notification3:
    name: Send Notification 3
    needs: [ test ]
    if: ${{ !success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        run: echo "This would send a notificaiton"
  send-notification4:
    name: Send Notification 4
    needs: [ test ]
    if: cancelled()
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        run: echo "This would send a notificaiton"
