name: Deploy Docs

on:
  push:
    branches-ignore:
      - 'gh-pages'
      - 'dependabot/**'
    tags:
      - '**'
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch (partial build)
        if: github.ref_type == 'branch'
        run: sleep 10 && echo 'Hello, world'
      - name: Dispatch (full build)
        if: github.ref_type == 'tag'
        run: sleep 10 && echo 'Hello, world'
